### ISSUE TITLE
TypeError: write_feather() got an unexpected keyword argument 'compression'

### ISSUE THREAD

**Issue by hcph** [aertslab/create_cisTarget_databases#23]
Hello, thank you for developing such powerful tool. I met a question that hard to solve, the command is as following: 
fasta_filename="test.fa"
motifs_dir="motifs_cb_format"
motifs_list_filename="motifs.lst"
db_prefix="st"
nbr_threads=20
cd /public/home/chaohe/create_cisTarget_databases
###Score all motifs at once and create rankings
create_cistarget_motif_databases.py \
-f "${fasta_filename}" \
-M "${motifs_dir}" \
-m "${motifs_list_filename}" \
-o "${db_prefix}" \
-t "${nbr_threads}"

when running this, I would get one error:
Scoring 530 motifs with Cluster-Buster took: 3.247628 seconds

Writing cisTarget regions vs motifs scores db: "st.motifs_vs_regions.scores.feather"
Traceback (most recent call last):
  File "/public/home/chaohe/create_cisTarget_databases/create_cistarget_motif_databases.py", line 539, in <module>
    main()
  File "/public/home/chaohe/create_cisTarget_databases/create_cistarget_motif_databases.py", line 490, in main
    write_db(ct_db=ct_scores_db_motifs_vs_regions_or_genes, db_prefix=db_prefix)
  File "/public/home/chaohe/create_cisTarget_databases/create_cistarget_motif_databases.py", line 480, in write_db
    version=2,
  File "/public/home/chaohe/create_cisTarget_databases/cistarget_db.py", line 1208, in write_db
    version=version,
TypeError: write_feather() got an unexpected keyword argument 'compression'

![image](https://user-images.githubusercontent.com/71759220/179402088-ade3ebd7-481a-4def-aecb-2bf134501585.png)

Could you please help me? Thank you very much!

**Comment by hcph** [comment]
This all about the environmental error of conda
