### ISSUE TITLE
 build mm10 regions based databases

### ISSUE THREAD

**Issue by WGLUN** [aertslab/create_cisTarget_databases#40]
First thank for sharing such a powerful pipeline for chromatin and motif analysis.
I was trying build a mm10 database based on regions defined in ATACseq following your tutorial.
However, I encounter an unexpected error. It seems it is related to motif files and annotation file. 
The motif files were download here:
https://resources.aertslab.org/cistarget/motif_collections/v10nr_clust_public/
Could you help on how to get this resolved?
Thanks

The output is like this,
Traceback (most recent call last):
  File "/usr/local/cisTarget_databases/bin//create_cistarget_motif_databases.py", line 572, in <module>
    main()
  File "/usr/local/cisTarget_databases/bin//create_cistarget_motif_databases.py", line 355, in main
    ) = get_motif_id_to_filename_and_nbr_motifs_dict(
  File "/usr/local/cisTarget_databases/bin/clusterbuster.py", line 102, in get_motif_id_to_filename_and_nbr_motifs_dict
    raise OSError(
OSError: Error: Cluster-Buster motif filename "/users/working/singletons/metacluster_196.3	EcR_usp	EcR/usp	bergman	1.1	Hnf4a	0	None	None	0.265823	FBgn0003964	D. melanogaster	gene is orthologous to FBgn0003964 in D. melanogaster (identity = 26%) which is directly annotated for motif.cb" does not exist for motif metacluster_196.3	EcR_usp	EcR/usp	bergman	1.1	Hnf4a	0	None	None	0.265823	FBgn0003964	D. melanogaster	gene is orthologous to FBgn0003964 in D. melanogaster (identity = 26%) which is directly annotated for motif.

**Comment by WGLUN** [comment]
I figured out what happened!
Please disregard or delete this topic.
Thanks

**Comment by jonhsussman** [comment]
Hi @WGLUN, I find the same issue; would you mind describing what the solution was? 

Thanks, 
Jonathan

**Comment by WGLUN** [comment]
Hi, @jonhsussman I followed this discussion here https://github.com/aertslab/create_cisTarget_databases/issues/4 to build the motif list.

**Comment by ghuls** [comment]
@jonhsussman You used the motif2TF file.

The motif file should contain only 1 column with the motif IDs (Cluster-Buster motif filename basename without extension):

```bash
cd v10nr_clust_public/singletons

ls -1 *.cb | sed -e 's/\.cb$//' > /tmp/v10nr_cbust_public.txt
```
